### ISSUE TITLE
k8s-daemonset example doesn't work on Kubernetes 1.5.0

### ISSUE THREAD

**Issue by andela-ooladayo** [BuoyantIO/linkerd-examples#81] opened 2017-01-28 13:21 UTC
I try to set up linkerd on kubernetes 1.5.0 using https://github.com/BuoyantIO/linkerd-examples/tree/master/k8s-daemonset. I keep getting the error below for >> 
```http_proxy=$(kubectl get svc l5d -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"):4140 curl -s http://hello```
```No hosts are available for /http/1.1/GET/hello, Dtab.base=[/srv=>/#/io.l5d.k8s/default/http;/host=>/srv;/http/*/*=>/host;/host/world=>/srv/world-v1], Dtab.local=[].Remote Info: Not Available```

When I downgrade to kubernetes 1.4.0, it works
Anyone with an idea of what's is happening here.

**Comment by klingerf** [comment] 2017-01-30 18:09
Hey @andela-ooladayo, thanks for reporting this issue! And apologies that our setup is causing problems on 1.5. If you have it available, could you paste the full output from running `kubectl get svc l5d -o json` in your kubernetes 1.5 cluster?

**Comment by klingerf** [comment] 2017-02-02 00:47
Hmm, as I mentioned in #78, I tried deploying to kubernetes 1.5.2 and I didn't run into this issue. Judging by the error message, it looks like maybe the `hello` pods or service failed to start, but I'm not able to reproduce it. Can you confirm that you're still seeing this issue?

**Comment by andela-ooladayo** [comment] 2017-02-07 13:46
I am using 1.4.0 now and its working well

**Comment by klingerf** [comment] 2017-02-07 18:25
Ok, thanks for the update. Will close this for now, but will leave #78 open to track the external ip/host issue.

**Closed by klingerf** 2017-02-07 18:25 UTC
